### ISSUE TITLE
Array case sensitivity problem in ParamaterContainer

### ISSUE THREAD

**Issue by belgattitude** [zendframework/zend-db#101]
Just a small typo fix in `Adapter\ParameterContainer::setFromArray(Array $array)` method. Array should be in lowercase.

**Comment by weierophinney** [comment]
Just a quick note: the PHP engine doesn't care about the case in this situation, as this is a keyword. While it *should* be lowercase, it's not *required*. We'll still merge #103, though.

**Comment by belgattitude** [comment]
Thanks Matthew :)

**Comment by weierophinney** [comment]
Fixed with #103
