### ISSUE TITLE
proposal: zend-db events

### ISSUE THREAD

**Issue by brettmc** [zendframework/zend-db#13]
I think it would be useful and powerful to integrate events into zend-db, probably along similar lines to the way it's done in zend-cache.
A minimal set of useful events might be:
connect.[pre, post, exception]
disconnect.[pre, post, exception]
execute.[pre, post, exception]

We use Oracle database, and a couple of potential use cases I've thought of are:
1) run a query immediately after connecting to the database to initialize the connection (eg to set NLS settings)
2) disconnect from database after executing a query (if using a connection pool).

Thoughts?

**Comment by Ocramius** [comment]
@brettmc the idea is neat, but please consider following things:

 - Zend\Cache is likely dropping event support due to being too slow because of them (even with refactored EVM)
 - doctrine has greatly suffered from event support: people constantly put non-persistence concerns into the persistence layer

That said, the use-cases you have above seem legitimate, but can be implemented with oracle specific drivers.

**Comment by brettmc** [comment]
@Ocramius that sounds reasonable, EVM does seem fairly chatty, but I was thinking of how to do it the most 'zendy' and flexible way -- my initial thoughts were just being able to inject a post-connect and post-query callback function.
When you say 'with oracle specific drivers', do you mean within Adapter\Driver\Oci8 (and possible Pdo too)? Maybe something that looks like:
```php
$db = new \Zend\Db\Adapter\Adapter($options);
if($db->getDriver() instanceof CallbackEnabledInterface {
  $db->getDriver()->setPostConnectCallback(function($connection){
    $stmt = oci_parse($connection, 'select * from dual');
    //...
  });
}
```

**Comment by brettmc** [comment]
@Ocramius a tradeoff on feature/performance might be having to enable events as part of adapter initialization?
```php
$db = new \Zend\Db\Adapter\Adapter(array('use_events' => true, /* ... */));
```
and within the adapters themselves:
```php
if($this->isUsingEvents()) {
  return $this->getEventManager()->trigger(new Event('dbconnect.pre', $this, $this->options));
```
?

**Comment by Ocramius** [comment]
> `if($this->isUsingEvents()) {`

This would be the worst of both worlds: config-enabled features that are very hard to debug.

No, just use wrappers please :-\

**Comment by brettmc** [comment]
ok, i'll close this request.
