### ISSUE TITLE
Currently Supported Data Types in DDL Abstraction

### ISSUE THREAD

**Issue by myabe** [zendframework/zend-db#148]
There is no TEXT in Currently Supported Data Types.
However, you can use to write the code. Is it okay to use?

**Comment by froschdesign** [comment]
This is a bug in the documentation, because the data type is [already there](https://github.com/zendframework/zend-db/blob/master/src/Sql/Ddl/Column/Text.php).

Thanks for reporting!

**Comment by samsonasik** [comment]
I've created PR #149 for it.
