### ISSUE TITLE
Pdo driver is passing platform & platform_options to PDO

### ISSUE THREAD

**Issue by alshayed** [zendframework/zend-db#185]
I'm using pdo_ibm and if you specify the platform & platform_options keys on the zend-db Adapter constructor, it ultimately passes them on to the PDO constructor. Unfortunately with pdo_ibm it seems to silently ignore any other options after that, so this is bad. The good news is that if I put the platform & platform_options keys last on the Adapter constructor array that lets me work around the issue.

I think in src/Adapter/Driver/Pdo/Connection.php it should ignore the platform & platform_options keys in connect() when it's building the new driver options array. Ie just before line 210 (the default case) it should have case statements for platform & platform_options with only a break so it ignores them.

I'd be happy to submit a pull request for this if people agree - just want to make sure that this is the "right way" to do it. I have not tried to reproduce this with other pdo drivers, I'm not sure if it's an issue with the base PHP PDO implementation or specific to pdo_ibm.

Thanks!
Brandon

**Comment by ezimuel** [comment]
Closing this because is not an issue, as reported in #189.
