### ISSUE TITLE
Zend\DB\SQL  order() only allow one space between field name and  DESC|ASC  

### ISSUE THREAD

**Issue by comeUpWithItLater** [zendframework/zend-db#192]
`
$select = $this->tableGateway->getSql() ->select();
//... 
$select  ->order("date_added DESC");  // one space  between  "date_added" and  "DESC"
echo  $select->getSqlString($this->dbAdapter->getPlatform());   // SELECT ... ORDER BY date_added DESC

$select  ->order("date_added   DESC");  // more than 2 spaces  between  "date_added" and  "DESC"
echo  $select->getSqlString($this->dbAdapter->getPlatform());   // SELECT ... ORDER BY date_added ASC <- not DESC !!!!
`

so  only one space is allowed between field name and  DESC|ASC, I can't say that this is a bug/ issue

**Comment by alextech** [comment]
Thank you for report!

**Comment by ezimuel** [comment]
Fixed in https://github.com/zendframework/zend-db/pull/205
