### ISSUE TITLE
Zend\Db\Sql\Ddl\CreateTable cannot set Encoding

### ISSUE THREAD

**Issue by maxvt0** [zendframework/zend-db#207]
I am trying to build Database with Zend\Db\Sql\Ddl but i cannot find anywhere informations on how to add encoding to CreateTable. I found this feature Request (https://github.com/zendframework/zendframework/issues/6273) but if i am not wrong it is closed. 
Is this feature implemented or do i have to build query by SQL to achieve  this?

**Comment by froschdesign** [comment]
> do i have to build query by SQL to achieve this?

Right.

**Comment by ezimuel** [comment]
We need volunteer to work on this feature, as reported here https://github.com/zendframework/zendframework/issues/6273.

**Comment by alextech** [comment]
Closed by accident?

**Comment by alextech** [comment]
@maxvt0 By "encoding" do you mean collation of a column? `column_name <data_type> COLLATE Collation_name`?  I do not see in SQL server syntax description at https://msdn.microsoft.com/en-us/library/ms174979.aspx to do tablewide encoding unless it is FILETABLE.

**Comment by maxvt0** [comment]
By encoding i meant `DEFAULT CHARSET` in SQL Query. For me when it was not set it created table with `latin1` but i needed `utf8mb4`.

**Comment by melnychukvitaliy** [comment]
how i can add engine or charset by creation table with DDL?

**Comment by maxvt0** [comment]
I made it this way:

`use Zend\Db\Sql\Ddl\AlterTable;
use Zend\Db\Sql\Ddl\Column\ColumnInterface;
use Zend\Db\Sql\Ddl\Constraint\AbstractConstraint;
use Zend\Db\Sql\Ddl\CreateTable;
use Zend\Db\Sql\Ddl\DropTable;
use Zend\Db\Sql\Sql;
use Zend\Db\TableGateway\Feature\GlobalAdapterFeature;


$adapter = GlobalAdapterFeature::getStaticAdapter();

$table = new CreateTable("table_name");
$table->addColumn(....);
.
.
.

$sql = new Sql($adapter);

$query = $sql->buildSqlString($table);
$query .=  " ENGINE=InnoDB DEFAULT CHARSET=" . DB_CHARSET;`

**Comment by melnychukvitaliy** [comment]
Thanks, I use the same way))
