### ISSUE TITLE
Zend DB SQLSRV: Prepared params not working

### ISSUE THREAD

**Issue by minimaex** [zendframework/zend-db#241]
Hello, Zend Select with SQLSRV is only working with this method:
$this->tableGateway->select(array("Personalnummer = $personalnumber"));

With the other method
$this->tableGateway->select(array("Personalnummer" => $personalnumber));
is it not working.

Please add the second method to the code like its written in the Tutorial:
https://framework.zend.com/manual/2.4/en/user-guide/skeleton-application.html

**Comment by froschdesign** [comment]
@ezimuel or @alextech 
Can you confirm this problem?

**Comment by minimaex** [comment]
Other users confirmed it too:
http://stackoverflow.com/questions/42859322/zend-2-sqlsrv-prepareparams-is-not-being-set

**Comment by alextech** [comment]
@minimaex what is your connection driver? PHP supports parameterized queries only through PDO. Therefore, to get `array("Personalnummer" => $personalnumber)` to work, you need to have configuration `driver` key be `pdo_sqlsrv`. Sounds like you have `'driver' => 'Sqlsrv'`

**Comment by minimaex** [comment]
It was Sqlsrv, thank you its working now! :)
