### ISSUE TITLE
sql server parameter binding

### ISSUE THREAD

**Issue by brettmc** [zendframework/zend-db#254]
Hi,
I think parameterized queries via the sql server adapter do not work. I've looked fairly hard at the code, and run it through a debugger (focussing on Zend\Db\Adapter\Driver\Sqlsrv\Statement::prepare() and ::bindParametersFromContainer() ) and it really looks to me like it should work.

I've submitted a pull request, https://github.com/zendframework/zend-db/pull/253 which adds two integration tests for sql server. You'll see that parameter binding works with `pdo_sqlsrv`, but not with `sqlsrv`.

**Comment by Ocramius** [comment]
@brettmc closing this one as you already reported this in #253
