### ISSUE TITLE
False values for left outer and right outer join

### ISSUE THREAD

**Issue by tdutrion** [zendframework/zend-db#26]
`Zend\Sql\Select` contains constant declaration for both left and right outer join as follow:

```
const JOIN_OUTER_RIGHT = 'outer right';
const JOIN_OUTER_LEFT  = 'outer left';
```

Unfortunately, as described in the [wikipedia article](https://en.wikipedia.org/wiki/Join_(SQL)#Left_outer_join) for instance, values should be respectively `left outer` and `right outer` instead of `outer left` and `outer right`.

**Comment by weierophinney** [comment]
Closed with #27
