### ISSUE TITLE
Potential issue on master - after merging #276

### ISSUE THREAD

**Issue by webimpress** [zendframework/zend-db#285]
As noted to @ezimuel on Slack we have potential issue here:
https://github.com/zendframework/zend-db/commit/bef0d5ab124a6176e239d3fdac588a75cc2585a0#diff-1b78954777bbbf9668cb36aef77507c2R248 in case of `else` (after merging PR #276).

It should be verified by unit tests and fixed.

/cc @remicollet

**Comment by remicollet** [comment]
I don't think we can have something else than an aray or a string.

So I deliberately keep this missing else, but feel free to improve

**Comment by ezimuel** [comment]
@remicollet this means we can replace `elseif (condition)` with a simple `else`?
