### ISSUE TITLE
Object is a reserved word in PHP 7.2

### ISSUE THREAD

**Issue by WellingGuzman** [zendframework/zend-db#290]
Since php 7.2 `Object` is a reserved word. Ref: http://php.net/manual/en/reserved.other-reserved-words.php

### Expected results

Work on php 7.2

### Actual results

```
Fatal error: Cannot use Zend\Db\Metadata\Object as Object because 'Object' is a special class name in `src/Metadata/Source/AbstractSource.php` on line 14
```

**Comment by alextech** [comment]
Fixed in #276
