### ISSUE TITLE
order by rand()

### ISSUE THREAD

**Issue by ozzpy** [zendframework/zend-db#320]
Sql with $select->order("rand()") produce invalid sql statement

CODE:

    $sql    = new Sql($this->dbAdapter);
    $select = $sql->select(
       ['a'=>$this->table]
    );

    $select->order("RAND() ASC");
    $select->limit(1);

    $stt = $sql->prepareStatementForSqlObject($select);
    $res = $stt->execute();

Result: 

    SELECT `a`.* FROM `mytable` AS `a` ORDER BY `RAND``(``)` ASC LIMIT 1

PS: I can do it manually

        $sqlString = "SELECT `a`.* FROM `mytable` AS `a` ORDER BY RAND() ASC LIMIT 1";
        $select    = $this->dbAdapter->getDriver()->createStatement($sqlString);
        $res       = $select->execute();

**Comment by ozzpy** [comment]
My bad :( Just found how to fix this
        $sql = new Sql($this->dbAdapter);
        $select = $sql->select(
            ['a'=>$this->table]
        );

        $select->order([new Expression("RAND() ASC")]);
        $select->limit(1);

        $stt = $sql->prepareStatementForSqlObject($select);
        $res = $stt->execute();

**Comment by Ocramius** [comment]
Please don't ever`ORDER BY RAND()`, as it has an undefined computational complexity
