### ISSUE TITLE
Invalid outer join constants

### ISSUE THREAD

**Issue by iarro** [zendframework/zend-db#33]
In Zend\Db\Sql\Select class are two invalid constants JOIN_OUTER_RIGHT and JOIN_OUTER_LEFT.  Their values are 'outer right' / 'outer left', but correct values are 'right outer' / 'left outer'. 
I checked this bug in MySql and it produce syntax error. Same problem is probably in PostgreSql (see documentation)

**Comment by Maks3w** [comment]
This was fixed on 2.6.0 https://github.com/zendframework/zend-db/pull/27
