### ISSUE TITLE
AuthDbTable

### ISSUE THREAD

**Issue by zhushaolei** [zendframework/zend-db#350]
- [ ] I was not able to find an [open](https://github.com/zendframework/zend-db/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-db/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [ ] This is not a question. (Questions should be asked on [slack](https://zendframework.slack.com/) ([Signup for Slack here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

Provide a narrative description of what you are trying to accomplish.

### Code to reproduce the issue

```php
```

**Comment by froschdesign** [comment]
@zhushaolei 
The description of this issue is incomplete. Please update the title and description otherwise we have to close this issue report. Thanks!
