### ISSUE TITLE
Expression placeholder exception

### ISSUE THREAD

**Issue by slifin** [zendframework/zend-db#374]
- [x] I was not able to find an [open](https://github.com/zendframework/zend-db/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-db/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [x] This is not a question. (Questions should be asked on [slack](https://zendframework.slack.com/) ([Signup for Slack here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

Provide a narrative description of what you are trying to accomplish.
Trying to create an expression with named parameters

### Code to reproduce the issue

```php
$expression =
    new Expression(':a + :b', [':a' => 1, ':b' => 1]);

(new Select())
    ->columns([$expression]);
```

### Expected results
```sql
SELECT 1 + 1 AS Expression1
```
### Actual results

```bash
Zend\Db\Sql\Exception\RuntimeException: The number of replacements in the expression does not match the number of parameters
in /vendor/zendframework/zend-db/src/Sql/Expression.php on line 151
```

### Context
Original code was introduced here: 
https://github.com/zendframework/zend-db/pull/112/commits/d8d096c08de0c37cc96b6b91da652f42e06a9194
Strict checking introduced here:
https://github.com/zendframework/zend-db/commit/4ce85654736c32d13c0f55cbcbd1884207690a78

### Possible Solution
Seems like the regex check on this line:
 https://github.com/zendframework/zend-db/blob/master/src/Sql/Expression.php#L149 
should be compared with `!==` not `===`

The other thing that would need to be considered is the same placeholder being used in multiple placeholders (which is what the test in https://github.com/zendframework/zend-db/pull/112/commits/d8d096c08de0c37cc96b6b91da652f42e06a9194 checks for)

Maybe retrieve all placeholders from string with regex then array_unique them then count them?

**Comment by slifin** [comment]
After applying the fix for this (3a98cea) to my own local copy of zend-db 

I get the following result:
```sql
SELECT :a + :b AS Expression1
```
from:

```php
$expression =
    new Expression(':a + :b', [':a' => 1, ':b' => 2]);

$select = new Select();
$select->columns([$expression]);
```

Instead of what I expected:
```sql
SELECT 1 + 2 AS Expression1
```

**Comment by webimpress** [comment]
@slifin I've checked and it is like that, but I think it is separate issue.
Converting expression with named parameters to string is not working properly... And it looks there is no any tests around it.

The test case:
```php
    public function testIntegrationWithSelect()
    {
        $expression = new Expression(':a + :b', ['a' => 1, 'b' => 2]);

        $select = new Select();
        $select->columns([$expression]);

        self::assertSame(
            'SELECT 1 + 2 AS Expression1',
            $select->getSqlString(new TrustingSql92Platform())
        );
    }
```

and the result:
```
Failed asserting that two strings are identical.
Expected :'SELECT 1 + 2 AS Expression1'
Actual   :'SELECT :a + :b AS Expression1'
```

I will have a look on it in free time.

**Comment by slifin** [comment]
Thank you, should I make a separate issue?
