### ISSUE TITLE
getHelpers is a void method

### ISSUE THREAD

**Issue by chris-kruining** [zendframework/zend-db#379]
https://github.com/zendframework/zend-db/blob/4c68f2c33beb76d63a59c5bd5e6c96c9763966d7/src/Adapter/Adapter.php#L237

As far as I can see this method is now little more than a waste of cpu cycles, is this method correct as is or should it return `$functions`?

**Comment by webimpress** [comment]
@chris-kruining I believe it should return `$functions` as you've noted.
As I can see this method is not used anywhere in the codebase.

Anyway, would you like to submit PR with the hotfix, please?

**Comment by chris-kruining** [comment]
wouldn't it be better in this case to deprecate the whole method?

**Comment by webimpress** [comment]
Can do as well. I was trying to find where it was used, but I haven't found anything.
Looks like added 7 years ago and then just CS fixes on it... Probably it was never used as it is unusable like that from the very beginning.

**Comment by chris-kruining** [comment]
hmm, just speculating, but if unusable for 7 years. go all in and remove?

**Comment by webimpress** [comment]
Yeah, that sounds as the best idea in that case, imho.

/cc @ezimuel

**Comment by chris-kruining** [comment]
closing, just need to await the PR to merge
