### ISSUE TITLE
\Zend\Db\Adapter\Driver\Pdo\Connection::rollback error

### ISSUE THREAD

**Issue by sorkl** [zendframework/zend-db#385]
https://github.com/zendframework/zend-db/blob/4c68f2c33beb76d63a59c5bd5e6c96c9763966d7/src/Adapter/Driver/Pdo/Connection.php#L345
the function  code like bellow  maybe  more better
```
    public function rollback()
    {
        if (!$this->isConnected()) {
            throw new Exception\RuntimeException('Must be connected before you can rollback');
        }

        if (!$this->inTransaction()) {
            throw new Exception\RuntimeException('Must call beginTransaction() before you can rollback');
        }

        if (0 === $this->nestedTransactionsCount) {
            $this->resource->rollBack();
            $this->nestedTransactionsCount = 0;
        }

        return $this;
    }
```

**Comment by webimpress** [comment]
@sorkl Would you like submit PR with the change and unit test? Thanks!

**Comment by usuyukiso** [comment]
I have similar issue  
Must call beginTransaction() before you can rollback In Zend\Db\Adapter\Driver\Pdo\Connection.php line 353.
Even though it was transaction. Also checked that it works with php 5.6, but fails with php7.2

I use libraries:
zendframework/zend-db     2.10.0
zendframework/zend-stdlib 3.2.1

**Comment by michalbundyra** [comment]
See: #390. Closing as "won't fix".
