### ISSUE TITLE
Expression does not support very complex query

### ISSUE THREAD

**Issue by netroby** [zendframework/zend-db#39]
The origin sql 
```
select max(convert(SUBSTRING_INDEX(order_uniqid,'-',-1), unsigned int)) as maxid from table
```
I want to write code like
```
$select->from($tablename)->column([maxid => new Expression('max(convert(SUBSTRING_INDEX(order_uniqid,'-',-1), unsigned int))')]; 
```
But Zend DB will never work.

Show errror:
```
Supplied expression must be a string.
```

the example order_uniqid may looks like

2343-234243-323434

**Comment by weierophinney** [comment]
On Sep 22, 2015 3:26 AM, "netroby" <notifications@github.com> wrote:
>
> The origin sql
>
> select max(convert(SUBSTRING_INDEX(order_uniqid,'-',-1), unsigned int))
as maxid from table
>
> I want to write code like
>
> $select->from($tablename)->column([maxid => new
Expression('max(convert(SUBSTRING_INDEX(order_uniqid,'-',-1), unsigned
int))')];

Check your quotes; as written, this is a subtraction expression with two
segments: PHP

- `max(convert(SUBSTRING_INDEX(order_uniqid,`
- `,-1), unsigned int))`

The single quotes around the `-` are terminating the first string, creating
a literal token that tells PHP you want to subtract the two strings.

Two options:

- use double quotes at the start and end of the string
- escape the single quotes surrounding the `-` character

**Comment by netroby** [comment]
Thanks. i fixed it .
