### ISSUE TITLE
Redirect from zendframework/Component_ZendDb ?

### ISSUE THREAD

**Issue by samizdam** [zendframework/zend-db#44]
Now I install my old project, with 1 dependency — zend-db. And catch this 

/*************************************/
ERROR: Repository not found.

Please make sure you have the correct access rights
and the repository exists.
/*************************************/

When I run composer up, I install required version (2.3) from this repo without problem. 
But what about support for legacy projects?

**Comment by weierophinney** [comment]
The repo address has changed, and the new repo has all historical versions.
Run `composer update zendframework/zend-db`, and it will resolve to the new
location.
